/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyzmanagment;


import java.util.regex.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mical
 */
public class CalculateSalary extends javax.swing.JFrame {
    Connection con;
    
    public CalculateSalary() {
        double netsalary,gasAllowance=5000,mobileallowance=2000,epf,etf,securitiytax,incometax,medicaretax,
                monthsalary,hourlysalary,fixedslary,basicsalary=50000,sal,tax1;
        try
        {
         DBConnection obj=new DBConnection();
         con=obj.GetConnection();
        }
        catch(Exception ex)
       {
            JOptionPane.showMessageDialog(null, "error connecting to database"+ ex,
                    "Login Form",JOptionPane.ERROR_MESSAGE);
       }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTaxFIncome = new javax.swing.JTextField();
        txtAEPF = new javax.swing.JTextField();
        txtAETF = new javax.swing.JTextField();
        txtGasAW = new javax.swing.JTextField();
        txtMobileAW = new javax.swing.JTextField();
        txtTaxSSecurity = new javax.swing.JTextField();
        txtTaxMedicare = new javax.swing.JTextField();
        txtNetSal = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEPFnumber = new javax.swing.JTextField();
        txtsal = new javax.swing.JTextField();
        numlab = new javax.swing.JLabel();
        slalab = new javax.swing.JLabel();
        txtWorkHour = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        hourlab = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ETF Amount");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("EPF Amount");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Gas Allowance");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Mobile Charge Allowance");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Social Security Tax");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Federal  Income Tax");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Medicare Tax");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Net Salary");

        txtTaxFIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxFIncomeActionPerformed(evt);
            }
        });

        txtAEPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAEPFActionPerformed(evt);
            }
        });

        txtAETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAETFActionPerformed(evt);
            }
        });

        txtGasAW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGasAWActionPerformed(evt);
            }
        });

        txtMobileAW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileAWActionPerformed(evt);
            }
        });

        txtTaxSSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxSSecurityActionPerformed(evt);
            }
        });

        txtTaxMedicare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxMedicareActionPerformed(evt);
            }
        });

        txtNetSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetSalActionPerformed(evt);
            }
        });

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalculate.setText("Calculate ");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(341, 341, 341))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCalculate)
                        .addComponent(jLabel9)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAEPF, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMobileAW, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAETF, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGasAW, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxSSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxFIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxMedicare, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNetSal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAEPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAETF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGasAW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMobileAW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTaxSSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTaxFIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTaxMedicare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNetSal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnsubmit)
                    .addComponent(btnclear))
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Register Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Claculate Salary");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Search Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Calcualate Employee Salary ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("EPF Number");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Basic Salary");

        txtEPFnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEPFnumberActionPerformed(evt);
            }
        });
        txtEPFnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEPFnumberKeyReleased(evt);
            }
        });

        txtsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsalKeyReleased(evt);
            }
        });

        numlab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numlab.setForeground(new java.awt.Color(255, 0, 0));

        slalab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        slalab.setForeground(new java.awt.Color(255, 0, 0));

        txtWorkHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkHourActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Work Hours");

        hourlab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hourlab.setForeground(new java.awt.Color(255, 0, 0));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Log out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEPFnumber))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtsal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtWorkHour, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hourlab, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slalab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(numlab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEPFnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(numlab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(slalab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtWorkHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(hourlab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEPFnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEPFnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEPFnumberActionPerformed

    private void txtWorkHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorkHourActionPerformed

    private void txtTaxFIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxFIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaxFIncomeActionPerformed

    private void txtAEPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAEPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAEPFActionPerformed

    private void txtAETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAETFActionPerformed

    private void txtGasAWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGasAWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGasAWActionPerformed

    private void txtMobileAWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileAWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileAWActionPerformed

    private void txtTaxSSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxSSecurityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaxSSecurityActionPerformed

    private void txtTaxMedicareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxMedicareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaxMedicareActionPerformed

    private void txtNetSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetSalActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        double netsalary,gasAllowance=5000,mobileallowance=2000,epf,etf,securitiytax,incometax,medicaretax,
                monthsalary,hourlysalary,fixedslary,basicsalary=50000,sal,salh,salh1;
        
       
        try
            
        {
            sal=  Double.parseDouble(txtsal.getText());
             securitiytax = sal * 2/100;
             incometax = sal * 4/100;
             medicaretax = sal * 3/100;
             epf = sal * 10/100;
             etf = sal * 5/100;
        boolean valid=true;
        if(txtEPFnumber.getText().isEmpty() && txtsal.getText().isEmpty() && txtWorkHour.getText().isEmpty())
            {
        JOptionPane.showMessageDialog(null,"Fill  the data ",
                "Salary Form",JOptionPane.ERROR_MESSAGE);
        valid=false;
            }
        else if
                (txtEPFnumber.getText().isEmpty() && txtsal.getText().isEmpty())
        {
            sal=  Double.parseDouble(txtsal.getText());
            
        valid=false;
        }
            
        if(valid)
        {
        String SalaryType=null;
        String Allowance=null;
        String EPF_ETF=null;
        String Tax=null;
        
        
        
        
        PreparedStatement stmtLogin=con.prepareStatement
        ("select * from EmployeeDetails1 where EpfNumber=?");
        
        stmtLogin.setString(1,txtEPFnumber.getText());
        
        
        ResultSet rs=stmtLogin.executeQuery();
        if(rs.next())
            
        {
        SalaryType=rs.getString("SalaryType");
        if(SalaryType.equals("Monthly"))
        {
              
              
        }
        
         if(SalaryType.equals("Hourly"))
         {
             
             sal=  Double.parseDouble(txtsal.getText());
              
         }
         if(SalaryType.equals("Fixed"))
         {
             sal=  Double.parseDouble(txtsal.getText());
         }
         Allowance=rs.getString("Allowance");
        if(Allowance.equals("Gas allowance"))
        {
             
             
             txtGasAW.setText(String.valueOf(gasAllowance));
        }
        if(Allowance.equals("Mobile Charge Allowance"))
        {
             
             
             txtMobileAW.setText(String.valueOf(mobileallowance));
        }
            
         if(Allowance.equals("Gas allowanceMobile Charge Allowance"))
         {
             
             
             txtGasAW.setText(String.valueOf(gasAllowance));
             txtMobileAW.setText(String.valueOf(mobileallowance));
             
         }
         
         
         EPF_ETF=rs.getString("EPF_ETF");
        if(EPF_ETF.equals("EPF"))
        { 
            
       
             epf = sal * 10/100;
             
             
               txtAEPF.setText(String.valueOf(epf)); 
        }
        
        if(EPF_ETF.equals("ETF"))
        {
            
             
             etf = sal * 5/100;
             
             
               txtAETF.setText(String.valueOf(etf));
        }
        
        
         if(EPF_ETF.equals("EPFETF"))
         {
             
            epf = sal * 10/100;
            etf = sal * 5/100;
            
            
               txtAEPF.setText(String.valueOf(epf));
               txtAETF.setText(String.valueOf(etf));
         }
        
         
         Tax=rs.getString("Tax");
        if(Tax.equals("Social Security"))
        {
            
             securitiytax = sal * 2/100;
             
             
               txtTaxSSecurity.setText(String.valueOf(securitiytax));
        }
        if(Tax.equals("Fedaral Income"))
        {
            
           
             incometax = sal * 4/100;
             
             
               txtTaxFIncome.setText(String.valueOf(incometax));
        }
        
         if(Tax.equals("Medicare"))
         {
             
             medicaretax = sal * 3/100;
             
             
               txtTaxMedicare.setText(String.valueOf(medicaretax));
         }
         if(Tax.equals("Social SecurityFedaral IncomeMedicare"))
         {
             
             securitiytax = sal * 2/100;
             incometax = sal * 4/100;
             medicaretax = sal * 3/100;
             
             
               txtTaxSSecurity.setText(String.valueOf(securitiytax));
               txtTaxFIncome.setText(String.valueOf(incometax));
               txtTaxMedicare.setText(String.valueOf(medicaretax));
               
         }
         netsalary = sal + (gasAllowance+mobileallowance) -(securitiytax+medicaretax-incometax+epf+etf);
         txtNetSal.setText(String.valueOf(netsalary));
         
        }
       
          else
             {
              JOptionPane.showMessageDialog(null,"fill the data ",
                "login Form",JOptionPane.ERROR_MESSAGE);
                  }
        
        }
        }
        
        catch(Exception ex)
                {
                JOptionPane.showMessageDialog(null,"Error message to system "+ ex);
                }
          
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        boolean valid=true;
        
                if(txtEPFnumber.getText().toString().isEmpty() ||
                txtsal.getText().toString().isEmpty() )
        {
        JOptionPane.showMessageDialog(null,"Field shoudnt be Blank ",
                "Register Form",JOptionPane.ERROR_MESSAGE);
        valid=false;
        }
          
          
        if(valid)
        {
        try
        {
        PreparedStatement statRegister=con.prepareStatement
        ("insert into SalaryRecord values(?,?,?,?,?,?,?,?,?,?)");
        statRegister.setString(1,txtEPFnumber.getText());
        statRegister.setString(2,txtsal.getText());
        statRegister.setString(3,txtAEPF.getText());
        statRegister.setString(4,txtAETF.getText());
        statRegister.setString(5,txtGasAW.getText());
        statRegister.setString(6,txtMobileAW.getText());
        statRegister.setString(7,txtTaxSSecurity.getText());
        statRegister.setString(8,txtTaxFIncome.getText());
        statRegister.setString(9,txtTaxMedicare.getText());
        statRegister.setString(10,txtNetSal.getText());
        
        
       
        int noRows= statRegister.executeUpdate();
        if(noRows>0)
        {
        JOptionPane.showMessageDialog(null,"new Salary record registerd ");
        }
        
        }
        catch (Exception ex)
        {
           JOptionPane.showMessageDialog(null,"Error encunterd while inserting data into database "+ex); 
        }
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtEPFnumber.setText("");
        txtsal.setText("");
        txtAEPF.setText("");
        txtAETF.setText("");
        txtGasAW.setText("");
        txtMobileAW.setText("");
        txtTaxSSecurity.setText("");
        txtTaxFIncome.setText("");
        txtTaxMedicare.setText("");
        txtNetSal.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtEPFnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEPFnumberKeyReleased
        String PATTERN="^[a-zA-Z](,30)$";
        Pattern patt= Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtEPFnumber.getText());
        if(match.matches()){
        numlab.setText("Wrong input Type");
        }
        else {
            numlab.setText(null);
        }
    }//GEN-LAST:event_txtEPFnumberKeyReleased

    private void txtsalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalKeyReleased
        String PATTERN="^(0-9)(0,12)$";
        Pattern patt= Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtsal.getText());
        if(match.matches()){
        slalab.setText("Wrong input Type");
        }
        else {
            slalab.setText(null);
        }
    }//GEN-LAST:event_txtsalKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(null,"Succsessfully Log out");
             LoginUI form= new LoginUI();
             form.setVisible(true);
             form.pack();
             form.setLocationRelativeTo(null);
             this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      JOptionPane.showMessageDialog(null,"RegisterEmployee");
             RegisterEmployee form= new RegisterEmployee();
             form.setVisible(true);
             form.pack();
             form.setLocationRelativeTo(null);
             this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       JOptionPane.showMessageDialog(null,"SearchEmpDetails");
             SearchEmpDetails form= new SearchEmpDetails();
             form.setVisible(true);
             form.pack();
             form.setLocationRelativeTo(null);
             this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null,"CalculateSalary");
             CalculateSalary form= new CalculateSalary();
             form.setVisible(true);
             form.pack();
             form.setLocationRelativeTo(null);
             this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel hourlab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel numlab;
    private javax.swing.JLabel slalab;
    private javax.swing.JTextField txtAEPF;
    private javax.swing.JTextField txtAETF;
    private javax.swing.JTextField txtEPFnumber;
    private javax.swing.JTextField txtGasAW;
    private javax.swing.JTextField txtMobileAW;
    private javax.swing.JTextField txtNetSal;
    private javax.swing.JTextField txtTaxFIncome;
    private javax.swing.JTextField txtTaxMedicare;
    private javax.swing.JTextField txtTaxSSecurity;
    private javax.swing.JTextField txtWorkHour;
    private javax.swing.JTextField txtsal;
    // End of variables declaration//GEN-END:variables
}
